### ISSUE TITLE
What is the maximum frame rate it supports?

### ISSUE THREAD

**Issue by liangzoey** [logtd/ComfyUI-MochiEdit#1]
Hello, as the title suggests, what is the maximum frame rate it supports for video generation? Is there any limit? I got an error when trying with 64 fps.

**Comment by logtd** [comment]
Hi, i'm not sure which node or setting you're talking about. If the error is on the last node that shows the video those come from https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite and you'll have to ask there
