### ISSUE TITLE
Deterministic Sampling Fixed Seed

### ISSUE THREAD

**Issue by samhodge-aiml** [logtd/ComfyUI-MochiEdit#11]
maybe I am missing something.

But I thought if I created Many .mp4 files and each of max VRAM length with rebatching that I could run out a video of any length.

This seems to be an important feature.

But the sampler changes the seed and I get a new look to the video.

Example .json file attached and the video output

Output video
https://github.com/user-attachments/assets/09447a20-fc20-467e-b76d-fecec9a2fbab

Script
[photoreal_78_frame.json](https://github.com/user-attachments/files/17656249/photoreal_78_frame.json)

Input Video
https://github.com/user-attachments/assets/6e2a7a54-5d31-41e8-a525-35157531cdb4

**Comment by logtd** [comment]
There's no seeds, but without the entire clip processing the whole time Mochi will inherently create different outputs. There's nothing to do about this besides process the entire clip.

Going to close this as I put some details in the other issue you opened.
