### ISSUE TITLE
Sampling nodes

### ISSUE THREAD

**Issue by fuzzyfazzy** [logtd/ComfyUI-MochiEdit#6]
When I load comfyui the sampling nodes are missing?

**Comment by kubakubkub** [comment]
yes I also have some missing nodes from the workflow
![image](https://github.com/user-attachments/assets/34294a4f-65ca-4a6d-8fe0-82b2a9df6d3f)

**Comment by Sinclou** [comment]
same for me... and i can't uptdate the package

**Comment by inferno46n2** [comment]
> yes I also have some missing nodes from the workflow ![image](https://private-user-images.githubusercontent.com/156693141/382776782-34294a4f-65ca-4a6d-8fe0-82b2a9df6d3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NDcxNTIsIm5iZiI6MTczMDc0Njg1MiwicGF0aCI6Ii8xNTY2OTMxNDEvMzgyNzc2NzgyLTM0Mjk0YTRmLTY1Y2EtNGE2ZC04ZmUwLTgyYjJhOWRmNmQzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxOTAwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjU4MzExMjYxMTgxYWQ0MzE3NTM1NTgyMmZkZGFjMDU2Mjg4YTFlYmRlN2E1ZmZmZjJhZDAwYjZhOTRhYjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QLRxUda7hQG1BhyytDnWzKfBhrQh626T71f1KYJFHng)

You need to also install Kijai's Mochi wrapper nodes https://github.com/kijai/ComfyUI-MochiWrapper

**Comment by inferno46n2** [comment]
> yes I also have some missing nodes from the workflow ![image](https://private-user-images.githubusercontent.com/156693141/382776782-34294a4f-65ca-4a6d-8fe0-82b2a9df6d3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NDcxNTIsIm5iZiI6MTczMDc0Njg1MiwicGF0aCI6Ii8xNTY2OTMxNDEvMzgyNzc2NzgyLTM0Mjk0YTRmLTY1Y2EtNGE2ZC04ZmUwLTgyYjJhOWRmNmQzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxOTAwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjU4MzExMjYxMTgxYWQ0MzE3NTM1NTgyMmZkZGFjMDU2Mjg4YTFlYmRlN2E1ZmZmZjJhZDAwYjZhOTRhYjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QLRxUda7hQG1BhyytDnWzKfBhrQh626T71f1KYJFHng)

You need to git pull Kijai's MochiWrapper nodes.

You are missing his update to include the VAE encoder and decoder

**Comment by Pancat009** [comment]
> > yes I also have some missing nodes from the workflow ![image](https://private-user-images.githubusercontent.com/156693141/382776782-34294a4f-65ca-4a6d-8fe0-82b2a9df6d3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NDcxNTIsIm5iZiI6MTczMDc0Njg1MiwicGF0aCI6Ii8xNTY2OTMxNDEvMzgyNzc2NzgyLTM0Mjk0YTRmLTY1Y2EtNGE2ZC04ZmUwLTgyYjJhOWRmNmQzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxOTAwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjU4MzExMjYxMTgxYWQ0MzE3NTM1NTgyMmZkZGFjMDU2Mjg4YTFlYmRlN2E1ZmZmZjJhZDAwYjZhOTRhYjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QLRxUda7hQG1BhyytDnWzKfBhrQh626T71f1KYJFHng)
> 
> You need to git pull Kijai's MochiWrapper nodes.
> 
> You are missing his update to include the VAE encoder and decoder

same issue, just need to get this node: https://github.com/kijai/ComfyUI-MochiWrapper

**Comment by fuzzyfazzy** [comment]
> yes I also have some missing nodes from the workflow
> ![image](https://github.com/user-attachments/assets/34294a4f-65ca-4a6d-8fe0-82b2a9df6d3f)
> 

    Weirdly - the one I used was the kijai one - it still comes up with the same missing nodes?

**Comment by logtd** [comment]
Hi, yes please make sure you have Kijai's node pack for MochiWrapper and that it is the most up to date version. We work together to make sure our most recent versions are synced (but expect the occasional drift).

**Comment by fuzzyfazzy** [comment]
Thank you! That worked - i didn't realise the kijai repo was updated so soon. Appreciate the help.
