### ISSUE TITLE
exception message:**'layers.0.weight'

### ISSUE THREAD

**Issue by mikeyimer** [logtd/ComfyUI-MochiEdit#8]
![捕啊啊啊啊啊aa获](https://github.com/user-attachments/assets/6a89b7ce-b595-42d2-8e05-34587368b590)
![捕啊啊啊获](https://github.com/user-attachments/assets/9b1fc946-b002-451f-a5c7-8733769f031f)

**Comment by zejacky** [comment]
I have the same issue. How did you resolve it. Thanks

**Comment by zejacky** [comment]
> I have the same issue. How did you resolve it. Thanks

Was solving it by using 'mochi_preview_vae_encoder_bf16_.safetensors'. Not the original vae decoder. My bad.

**Comment by nathanshipley** [comment]
So I fixed this by downloading this file:
https://huggingface.co/genmo/mochi-1-preview/blob/main/encoder.safetensors

And placing in 
`ComfyUI\models\vae\mochi`
